---
name: kitchen

"on":
  pull_request:
  push:
    branches:
      - main

defaults:
  env:
    working-directory: kitchen-tests

jobs:
  windows:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2022, windows-2019]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Install Chef
      uses: actionshub/chef-install@3.0.0
    - name: Kitchen converge
      uses: actionshub/test-kitchen@2.1.0
      env:
        CHEF_LICENSE: accept-no-persist
        KITCHEN_LOCAL_YAML: kitchen.exec.windows.yml
        working-directory: kitchen-tests
      with:
        suite: end-to-end
        os: ${{ matrix.os }}
        action: converge
        working-directory: kitchen-tests
    - name: Kitchen verify
      uses: actionshub/test-kitchen@2.1.0
      env:
        CHEF_LICENSE: accept-no-persist
        KITCHEN_LOCAL_YAML: kitchen.exec.windows.yml
      with:
        suite: end-to-end
        os: ${{ matrix.os }}
        action: verify

  macos:
    runs-on: macos-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
            clean: true
      - name: Install Chef
        uses: actionshub/chef-install@3.0.0
      - name: Kitchen converge
        uses: actionshub/test-kitchen@2.1.0
        env:
          CHEF_LICENSE: accept-no-persist
          KITCHEN_LOCAL_YAML: kitchen.exec.macos.yml
          working-directory: kitchen-tests
        with:
          suite: end-to-end
          os: ${{ matrix.os }}
          action: converge
          working-directory: kitchen-tests
      - name: Kitchen verify
        uses: actionshub/test-kitchen@2.1.0
        env:
          CHEF_LICENSE: accept-no-persist
          KITCHEN_LOCAL_YAML: kitchen.exec.macos.yml
        with:
          suite: end-to-end
          os: ${{ matrix.os }}
          action: verify

  linux:
    strategy:
      fail-fast: false
      matrix:
        os:
          - 'amazonlinux-2023'
          - 'centos-7'
          - 'almalinux-8'
          - 'almalinux-9'
          - 'debian-11'
          - 'debian-12'
          - 'fedora-latest'
          - 'opensuse-leap-15'
          - 'ubuntu-1804'
          - 'ubuntu-2004'
          - 'ubuntu-2204'
    runs-on: ubuntu-latest
    env:
      FORCE_FFI_YAJL: ext
      CHEF_LICENSE: accept-no-persist
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Install Chef
        uses: actionshub/chef-install@3.0.0
      - name: Kitchen converge
        uses: actionshub/test-kitchen@2.1.0
        env:
          CHEF_LICENSE: accept-no-persist
          KITCHEN_LOCAL_YAML: kitchen.dokken.yml
        with:
          suite: end-to-end
          os: ${{ matrix.os }}
          action: converge
          working-directory: kitchen-tests
      - name: Kitchen verify
        uses: actionshub/test-kitchen@2.1.0
        env:
          CHEF_LICENSE: accept-no-persist
          KITCHEN_LOCAL_YAML: kitchen.dokken.yml
          working-directory: kitchen-tests
        with:
          suite: end-to-end
          os: ${{ matrix.os }}
          action: verify

  # Amazon Linux 2 has an issue with systemctl (throws a timedatectl error)
  # if dokken container hosted on Ubuntu 22.04 or later. Lock to Ubuntu 20.04
  # for now.
  linux-2004-host:
    strategy:
      fail-fast: false
      matrix:
        os:
          - 'amazonlinux-2'
    runs-on: ubuntu-20.04
    env:
      FORCE_FFI_YAJL: ext
      CHEF_LICENSE: accept-no-persist
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Install Chef
        uses: actionshub/chef-install@3.0.0
      - name: Kitchen converge
        uses: actionshub/test-kitchen@2.1.0
        env:
          CHEF_LICENSE: accept-no-persist
          KITCHEN_LOCAL_YAML: kitchen.dokken.yml
          working-directory: kitchen-tests
        with:
          suite: end-to-end
          os: ${{ matrix.os }}
          action: converge
      - name: Kitchen verify
        uses: actionshub/test-kitchen@2.1.0
        env:
          CHEF_LICENSE: accept-no-persist
          KITCHEN_LOCAL_YAML: kitchen.dokken.yml
          working-directory: kitchen-tests
        with:
          suite: end-to-end
          os: ${{ matrix.os }}
          action: verify
