---
name: kitchen

"on":
  pull_request:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: kitchen-tests

jobs:
  windows:
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-2019
          - windows-2022
    runs-on: ${{ matrix.os }}
    env:
      CHEF_LICENSE: accept-no-persist
      KITCHEN_LOCAL_YAML: kitchen.exec.windows.yml
    steps:
    - uses: actions/checkout@v4
    - name: Install Chef
      uses: actionshub/chef-install@3.0.0
    - name: Kitchen test
      run: |
        kitchen converge end-to-end-${{ matrix.os }}
        echo "Last exit code: $?"
    - run: |
        kitchen verify end-to-end-${{ matrix.os }}
        echo "Last exit code: $?"

  macos:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
    runs-on: macos-latest
    env:
      CHEF_LICENSE: accept-no-persist
      KITCHEN_LOCAL_YAML: kitchen.exec.macos.yml
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
            clean: true
      - name: Install Chef
        uses: actionshub/chef-install@3.0.0
      - name: Kitchen test
        run: |
          kitchen converge end-to-end-${{ matrix.os }}
          echo "Last exit code: $?"
      - run: |
          kitchen verify end-to-end-${{ matrix.os }}
          echo "Last exit code: $?"

  linux:
    strategy:
      fail-fast: false
      matrix:
        os:
          - amazonlinux-2023
          - almalinux-8
          - almalinux-9
          - debian-11
          - debian-12
          - fedora-latest
          - opensuse-leap-15
          - rockylinux-8
          - rockylinux-9
          - ubuntu-1804
          - ubuntu-2004
          - ubuntu-2204
    runs-on: ubuntu-latest
    env:
      FORCE_FFI_YAJL: ext
      CHEF_LICENSE: accept-no-persist
      KITCHEN_LOCAL_YAML: kitchen.dokken.yml
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Install Chef
        uses: actionshub/chef-install@3.0.0
      - name: Kitchen test
        run: |
          kitchen converge end-to-end-${{ matrix.os }}
          echo "Last exit code: $?"
      - run: |
          kitchen verify end-to-end-${{ matrix.os }}
          echo "Last exit code: $?"

  # Amazon Linux 2 has an issue with systemctl (throws a timedatectl error)
  # if dokken container hosted on Ubuntu 22.04 or later. Lock to Ubuntu 20.04
  # for now.
  linux2:
    strategy:
      fail-fast: false
      matrix:
        os:
          - amazonlinux-2
    runs-on: ubuntu-20.04
    env:
      FORCE_FFI_YAJL: ext
      CHEF_LICENSE: accept-no-persist
      KITCHEN_LOCAL_YAML: kitchen.dokken.yml
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Install Chef
        uses: actionshub/chef-install@3.0.0
      - name: Kitchen test
        run: |
          kitchen converge end-to-end-${{ matrix.os }}
          echo "Last exit code: $?"
      - run: |
          kitchen verify end-to-end-${{ matrix.os }}
          echo "Last exit code: $?"

  linux3:
    strategy:
      fail-fast: false
      matrix:
        os:
          - amazonlinux-2
          # - amazonlinux-2023 # Bento Amazon Linux 2023 box is not available yet
          - almalinux-8
          - almalinux-9
          - debian-11
          - debian-12
          - fedora-latest
          - freebsd-13
          - freebsd-14
          - opensuse-leap-15
          - rockylinux-8
          - rockylinux-9
          - ubuntu-1804
          - ubuntu-2004
          - ubuntu-2204
    runs-on: ubuntu-latest
    env:
      CHEF_LICENSE: accept-no-persist
    steps:
      - uses: actions/checkout@v4
      - name: Install Vagrant and VirtualBox
        run: |
          sudo apt-get update
          sudo apt -y install apt-transport-https ca-certificates curl software-properties-common
          wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg
          wget -q https://www.virtualbox.org/download/oracle_vbox_2016.asc -O- | sudo apt-key add -
          wget -q https://www.virtualbox.org/download/oracle_vbox.asc -O- | sudo apt-key add –
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          echo "deb [arch=amd64] http://virtualbox.org/virtualbox/debian $(lsb_release -cs) contrib" | sudo tee /etc/apt/sources.list.d/virtualbox.list
          sudo apt-get update
          sudo apt-get install -y vagrant virtualbox
      - name: Install Chef
        uses: actionshub/chef-install@3.0.0
      - name: Kitchen test
        run: |
          kitchen converge end-to-end-${{ matrix.os }}
          echo "Last exit code: $?"
      - run: |
          kitchen verify end-to-end-${{ matrix.os }}
          echo "Last exit code: $?"
