---
name: kitchen

"on":
  pull_request:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: kitchen-tests

jobs:
  windows:
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-2019
          - windows-2022
    runs-on: {{ matrix.os }}
    env:
      CHEF_LICENSE: accept-no-persist
      KITCHEN_LOCAL_YAML: kitchen.exec.windows.yml
    steps:
    - uses: actions/checkout@v4
    - run: sudo apt-get update && sudo apt-get install -y vagrant virtualbox
    - name: Install Chef
      uses: actionshub/chef-install@3.0.0
    - name: Kitchen test
      run: |
        kitchen converge end-to-end-${{ matrix.os }}
        echo "Last exit code: $?"
    - run: |
        kitchen verify end-to-end-${{ matrix.os }}
        echo "Last exit code: $?"

  macos:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
    runs-on: macos-latest
    env:
      CHEF_LICENSE: accept-no-persist
      KITCHEN_LOCAL_YAML: kitchen.exec.macos.yml
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
            clean: true
      - name: Install Chef
        uses: actionshub/chef-install@3.0.0
      - name: Kitchen test
        run: |
          kitchen converge end-to-end-${{ matrix.os }}
          echo "Last exit code: $?"
      - run: |
          kitchen verify end-to-end-${{ matrix.os }}
          echo "Last exit code: $?"

  linux:
    strategy:
      fail-fast: false
      matrix:
        os:
          - amazonlinux-2023
          - almalinux-8
          - almalinux-9
          - debian-11
          - debian-12
          - fedora-latest
          - opensuse-leap-15
          - ubuntu-1804
          - ubuntu-2004
          - ubuntu-2204
    runs-on: ubuntu-latest
    env:
      FORCE_FFI_YAJL: ext
      CHEF_LICENSE: accept-no-persist
      KITCHEN_LOCAL_YAML: kitchen.dokken.yml
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Install Chef
        uses: actionshub/chef-install@3.0.0
      - name: Kitchen test
        run: |
          kitchen converge end-to-end-${{ matrix.os }}
          echo "Last exit code: $?"
      - run: |
          kitchen verify end-to-end-${{ matrix.os }}
          echo "Last exit code: $?"

  # Amazon Linux 2 has an issue with systemctl (throws a timedatectl error)
  # if dokken container hosted on Ubuntu 22.04 or later. Lock to Ubuntu 20.04
  # for now.
  linux2:
    strategy:
      fail-fast: false
      matrix:
        os:
          - amazonlinux-2
    runs-on: ubuntu-20.04
    env:
      FORCE_FFI_YAJL: ext
      CHEF_LICENSE: accept-no-persist
      KITCHEN_LOCAL_YAML: kitchen.dokken.yml
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Install Chef
        uses: actionshub/chef-install@3.0.0
      - name: Kitchen test
        run: |
          kitchen converge end-to-end-${{ matrix.os }}
          echo "Last exit code: $?"
      - run: |
          kitchen verify end-to-end-${{ matrix.os }}
          echo "Last exit code: $?"

  linux3:
    strategy:
      fail-fast: false
      matrix:
        os:
          - amazonlinux-2
          - amazonlinux-2023
          - almalinux-8
          - almalinux-9
          - debian-11
          - debian-12
          - fedora-latest
          - opensuse-leap-15
          - ubuntu-1804
          - ubuntu-2004
          - ubuntu-2204
    runs-on: ubuntu-latest
    env:
      CHEF_LICENSE: accept-no-persist
      # KITCHEN_LOCAL_YAML: kitchen.exec.windows.yml
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get update && sudo apt-get install -y vagrant virtualbox
      - name: Install Chef
        uses: actionshub/chef-install@3.0.0
      - name: Kitchen test
        run: |
          kitchen converge end-to-end-${{ matrix.os }}
          echo "Last exit code: $?"
      - run: |
          kitchen verify end-to-end-${{ matrix.os }}
          echo "Last exit code: $?"
