---
name: kitchen

"on":
  pull_request:
  push:
    branches:
      - main

jobs:
  windows:
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-10
          - windows-11
          - windows-2016
          - windows-2019
          - windows-2022
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: apt-get update && apt-get install -y vagrant virtualbox
    - name: Install Chef
      uses: actionshub/chef-install@3.0.0
    - name: Kitchen test
      env:
        CHEF_LICENSE: accept-no-persist
        # KITCHEN_LOCAL_YAML: kitchen.exec.windows.yml
      run: |
        cd kitchen-tests
        kitchen converge end-to-end-${{ matrix.os }}
    - run: kitchen verify end-to-end-${{ matrix.os }}

  macos:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
    runs-on: macos-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
            clean: true
      - name: Install Chef
        uses: actionshub/chef-install@3.0.0
      - name: Kitchen test
        env:
          CHEF_LICENSE: accept-no-persist
          KITCHEN_LOCAL_YAML: kitchen.exec.macos.yml
        run: |
          cd kitchen-tests
          kitchen converge end-to-end-${{ matrix.os }}
      - run: kitchen verify end-to-end-${{ matrix.os }}

  linux:
    strategy:
      fail-fast: false
      matrix:
        os:
          - amazonlinux-2
          - amazonlinux-2023
          - centos-7
          - almalinux-8
          - almalinux-9
          - debian-11
          - debian-12
          - fedora-latest
          - opensuse-leap-15
          - ubuntu-1804
          - ubuntu-2004
          - ubuntu-2204
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Install Chef
        uses: actionshub/chef-install@3.0.0
      - name: Kitchen test
        env:
          FORCE_FFI_YAJL: ext
          CHEF_LICENSE: accept-no-persist
          KITCHEN_LOCAL_YAML: kitchen.dokken.yml
        run: |
          cd kitchen-tests
                    kitchen converge end-to-end-${{ matrix.os }}
      - run: kitchen verify end-to-end-${{ matrix.os }}
